### ISSUE TITLE
linux version of dsm2 creates multiple echo files

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/dsm2#15]
dsm2 version: 8.2x
OS: linux

hydro and qual both create echo files and the main echo file is created with most of the information correctly, however a similar name with various special charaters appended is also created with mainly the initial header info that should have been written to the main echo file is also created. 

This is probably a lack of initialization of the filename in the fortran code.

**Comment by kjnam** [comment]
@dwr-psandhu Thanks for reporting it. It is a known issue, but it has not been addressed yet.
